seqsense/s3sync

LICENSE
Makefile
README.md
examples/logger/example.go
examples/simple/example.go
logger.go
s3sync.go
s3sync_test.go

Add license notices

---

.travis.yml
README.md

- We open sourced this library, and therefore now we can use codecov for free!
https://codecov.io/gh/seqsense/s3sync/src/147a96e90b9bc7a069199c9678d165db47aa0666/s3sync.go

Add codecov settings

---

.travis.yml

- In some builds, the amount of sleep doesn't look enough ex. https://travis-ci.com/seqsense/s3sync/jobs/280313285
- This PR changes the sleep duration from 10s to 15s.

Sleep longer in CI

---

renovate.json

- run `go mod tidy` post update
- only update `golang.org/x/` packages once a month
- add local timezone setting

Fix renovate settings

---

renovate.json

This PR changes base schedule of Renovate weekly from daily. 
Dealing with Renovate PRs every day sometimes bothers us 😓

Update Renovate scheduling

---

renovate.json

Fix #35. Current configuration doesn't work as expected.

Renovate: fix automerge configuration

---

option.go
option_test.go
s3sync.go

Pass option as a functional option.

Add option to set number of parallel jobs

---

README.md

docs: mention WithParallel in README

---

option.go
option_test.go
s3sync.go

Add option to specify ACL

---

Makefile
option.go
s3sync.go
s3sync_test.go

Equivalent of `aws s3 sync --delete`
closes #48

Add delete option

---

.travis.yml
Makefile
go.sum
s3sync_test.go
util_test.go

Splitted localstack setting to #72

Refactor test

---

.travis.yml
go.mod

and remove Go 1.13 as it's no longer supported

Update to Go 1.15

---

Makefile
s3sync.go
s3sync_test.go

Fix single file sync source path

---

option.go
option_test.go
s3sync.go

Add options to set s3 Uploader/Downloader options

---

.github/workflows/ci.yml

Update version matrix

---

.github/workflows/ci.yml
Makefile
renovate.json

Workaround error in localstack on test

---

s3path.go
s3sync.go

PR to fix issue "Wrong s3 path separator on Windows #180"

Fix s3 path separator on Windows

---

Makefile
README.md
s3sync.go
s3sync_test.go

Hello! I saw that the S3 to S3 functionality hadn't been implemented yet.
Let me know what you think or if anything should change. I don't contribute a lot to OSS so let me know if there is anything more you'd like to see here.
I'm not able to run tests locally as I don't have everything configured for that, so let's see what the CI tells us.
matthew

Add S3 to S3 copy functionality

---

MIGRATION.md
README.md

- https://github.com/seqsense/s3sync/issues/410
Also add migration guide

Update README for v2

---

go.mod

Remove toolchain version
